### ISSUE TITLE
The Readme.md still have rector-installer instead of extension-installer

### ISSUE THREAD

**Issue by sabbelasichon** [rectorphp/rector-installer#4]

**Comment by TomasVotruba** [comment]
It might be faster to edit file online and send PR than making this issue title :D 

You can actually use Github editor for there files, no need to git around locally.

**Comment by sabbelasichon** [comment]
Would have done it, but i have not found it on my iphone. Will do it in the morning 😀

**Comment by TomasVotruba** [comment]
I see. Phone hacking is a challenge :D 
(Just on my phone with rain all over the display 😂
