### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by ondrejmirtes** [rectorphp/rector-installer#6]
Hello,
this package is clearly and heavily inspired by `phpstan/extension-installer`: https://github.com/phpstan/extension-installer

But there's no mention of the original idea in README or LICENSE file.

`phpstan/extension-installer` is distributed under MIT license (https://github.com/phpstan/extension-installer/blob/master/LICENSE). While the MIT license is very permissive (see the wording) and allows you to copy the code without limitation, the original copyright notice should be preserved.

Please fix this so that the open-source spirit is preserved and we can continue making great work! Thanks.

**Comment by TomasVotruba** [comment]
Hi Ondra, 

sure, I usually refer original files with see in the code 👍 


@sabbelasichon Could you check this?

**Comment by sabbelasichon** [comment]
Sure. I am gonna fix this right now.

**Comment by sabbelasichon** [comment]
@ondrejmirtes Sorry for that by the way. That was definitely not my intention. Thank you for pointing it out.

**Comment by sabbelasichon** [comment]
And thank you for extraordinary work in the PHP ecosystem.

**Comment by ondrejmirtes** [comment]
@sabbelasichon Yeah, no problem, thank you :) I felt a little bit bad about pointing this out, but there would be no point to licenses if they were not enforced.

**Comment by sabbelasichon** [comment]
Not at all. The work is yours and you deserve it.

**Comment by sabbelasichon** [comment]
@ondrejmirtes Is this fine for you?

- https://github.com/rectorphp/extension-installer/pull/7/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
- https://github.com/rectorphp/extension-installer/pull/7/files#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

Or should i add also a copyright notice to the files itself? We don´t have one, so i would like to avoid it.

**Comment by ondrejmirtes** [comment]
This is totally fine 👍

**Comment by ondrejmirtes** [comment]
Thank you everyone!
